name: NuGet

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    uses: ./.github/workflows/_build.yml
    
  push-package:
    name: Publish NuGet Package
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Add nuget.org source
        run: dotnet nuget add source --name NUGET https://www.nuget.org

      - name: Push to nuget.org
        run: dotnet nuget push **/*.nupkg -s "NUGET" -k ${{ secrets.NUGET_APIKEY }}